# Generated by Django 3.0.4 on 2020-07-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200706_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='WillYouAttend',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendances',
            field=models.IntegerField(blank=True, default=1, verbose_name='Asistencias'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
